"""Bound S1-OW fixtures for read-only O3 checkpoints."""

from __future__ import annotations

from tests.g2_d3_s1os_fixtures import INVALID_FIXTURES, VALID_FIXTURES


VALID_CHECKPOINT_FIXTURES = {
    "OV_V_XXX": VALID_FIXTURES["OR_V_XXX"],
    "OV_V_YYY": VALID_FIXTURES["OR_V_YYY"],
}

SEQUENCE_FAILURE_FIXTURES = {
    "OV_I_UNKNOWN_FIRST": INVALID_FIXTURES["OR_I_UNKNOWN_FIRST"],
    "OV_I_UNKNOWN_INITIAL": INVALID_FIXTURES["OR_I_UNKNOWN_INITIAL"],
    "OV_I_FORMATION_DISABLED": INVALID_FIXTURES["OR_I_FORMATION_DISABLED"],
    "OV_I_SECOND_INVALID": INVALID_FIXTURES["OR_I_SECOND_INVALID"],
    "OV_I_SECOND_SOURCE_C0": INVALID_FIXTURES["OR_I_SECOND_SOURCE_C0"],
    "OV_I_SECOND_CONTACT_CROSS": INVALID_FIXTURES["OR_I_SECOND_CONTACT_CROSS"],
    "OV_I_SECOND_CONTACT_RESET": INVALID_FIXTURES["OR_I_SECOND_CONTACT_RESET"],
}

EXPECTED_CHAIN_ROLES = {
    "OV_V_XXX": "OP_CHAIN_XXX",
    "OV_V_YYY": "OP_CHAIN_YYY",
}
EXPECTED_VALUES = (0.5, 0.25, 0.125)
EXPECTED_COMPONENTS = (-0.25, -0.125, -0.375)
EXPECTED_COMPARISON_DIGEST = (
    "5c8d3b60bbc205594974f632a878472bf628426dc914af72514cf7b42e8a86a5"
)
DEFENSIVE_CODES = (
    "OU_COMPOSITION_IDENTITY_MISMATCH",
    "OU_CP0_EVALUATION_FAILED",
    "OU_CP1_EVALUATION_FAILED",
    "OU_CP2_EVALUATION_FAILED",
    "OU_CHECKPOINT_IDENTITY_MISMATCH",
    "OU_COMPONENT_IDENTITY_MISMATCH",
)
