from dataclasses import replace
import unittest
from mcm_field_organism.public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order import *
from mcm_field_organism.public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_preflight_acceptance import accept_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_preflight
from tools.audit_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_preflight import build_callable_factory_call_execution_release_final_preflight
class PublicAVReturnReplicationRepeatabilitySingleSlotCallableFactoryCallExecutionReleaseFinalOrderTests(unittest.TestCase):
 def setUp(self): self.release_final_preflight_acceptance_contract=accept_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_preflight(build_callable_factory_call_execution_release_final_preflight(1))
 def test_derives_one_final_unconsumed_step(self):
  o=order_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final(self.release_final_preflight_acceptance_contract); self.assertTrue(o.positive_final_preflight_acceptance_bound); self.assertTrue(o.exactly_one_final_lock_step_derived); self.assertTrue(o.final_lock_step_one_time); self.assertTrue(o.final_lock_step_unconsumed); self.assertFalse(o.actual_release_granted); self.assertTrue(o.final_order_complete)
 def test_execution_surfaces_remain_locked(self):
  o=order_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final(self.release_final_preflight_acceptance_contract)
  for f in ("actual_release_granted","callable_factory_reference_stored","callable_reference_stored","factory_function_called","callable_factory_called","callable_object_created","binding_performed","media_decode_allowed","receptor_feed_allowed","repeat_run_started","memory_claim_allowed","meaning_claim_allowed","organization_claim_allowed","ai_claim_allowed"):
   with self.assertRaises(PublicAVReturnReplicationRepeatabilitySingleSlotCallableFactoryCallExecutionReleaseFinalOrderError): replace(o,**{f:True})
  with self.assertRaises(PublicAVReturnReplicationRepeatabilitySingleSlotCallableFactoryCallExecutionReleaseFinalOrderError): execute_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order(o)
 def test_json_excludes_results_and_scores(self):
  p=public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order_to_jsonable(order_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final(self.release_final_preflight_acceptance_contract)); self.assertFalse(p["actual_release_granted"]); self.assertNotIn("result",p); self.assertNotIn("memory_score",p)
if __name__=="__main__": unittest.main()
