import argparse,json
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from audit_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_preflight_acceptance import build_callable_factory_call_execution_release_final_preflight_acceptance
from mcm_field_organism.public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order import order_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final,public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order_to_jsonable
def build_callable_factory_call_execution_release_final_order(i): return order_public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final(build_callable_factory_call_execution_release_final_preflight_acceptance(i))
def main(argv=None):
 p=argparse.ArgumentParser(); p.add_argument("--repeat-index",type=int,choices=(1,2,3),default=1); a=p.parse_args(argv); o=build_callable_factory_call_execution_release_final_order(a.repeat_index); print(json.dumps(public_av_return_replication_repeatability_single_slot_callable_factory_call_execution_release_final_order_to_jsonable(o),indent=2,sort_keys=True)); return 0 if o.final_order_complete else 1
if __name__=="__main__": raise SystemExit(main())
